### ISSUE TITLE
Add an option to do not switch to repl buffer on send command group

### ISSUE THREAD

**Issue by illia-danko** [J3RN/inf-elixir#15]
As a user I have the following setup:
- open a elixir code buffer on the left side;
- open a inf repl buffer on the right side;

Whenever I experiment with a function or a variable I evaluate it by either: `inf-elixir-send-buffer` once I've switched to file, `inf-elixir-send-region` or `inf-elixir-send-line`. That works, but I found tedious to switch back to the source code buffer every time after the evaluation. 

Proposal:
- add a custom variable to make the switch to a repl buffer being optional.

**Comment by J3RN** [comment]
Fixed by #16
