### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by rolandtritsch** [J3RN/inf-elixir#3]
https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

Would suggest to use the MIT license.

**Comment by J3RN** [comment]
That's the license that I typically use :smile: However, [Melpa recommends GPLv3](https://github.com/melpa/melpa/blob/master/CONTRIBUTING.org), though any "GPL compatible license" should work. I'll do a little bit more research and choose an appropriate license. Thanks for pointing this out!
